### ISSUE TITLE
Undefined reference to `pok_ports_names_max_len'

### ISSUE THREAD

**Issue by Etienne13** [pok-kernel/pok#11]
As a follow up on commit #10

When compiling the code generated from my tool, I get the following compilation error.

syscall.c:290: undefined reference to `pok_ports_names_max_len'

Indeed, pok_ports_names_max_len is defined as extern in syscall.c.

I guess the variable definition has to be generated by third party tools, but how to compute the expected value? If it is a constant, why wouldn't we use maccros like for most configuration parameters of POK?

Might be due to modifications in misc/mk/rules-main.mk?

**Comment by Etienne13** [comment]
Fixed the issue by adapting my code generator to define pok_ports_names_max_len variable.

**Comment by sduverger** [comment]
Hi Etienne,

Julien is right, there is a fix in my patch for #9 with an AWK one-liner to generate pok_port_names_max_len during compilation phase. Then this variable is extern in syscall.c and should be conditionally included only if we NEED_PORT.

I didn't touch your perl script and i think it might be the correct way to generate this variable, but if you do so, don't forget to remove my one-liner in the Makefile.

**Comment by Etienne13** [comment]
The fix was in my AADL to pok code generator (on another repository). 

I saw the AWK part but it seems the problem was in my tool and did not appear in previous versions for a reason I do not understand. I also had a problem in conflicting definitions of strlen but I fixed it in my latest commit: it appeared yesterday and did not show up before.

Note/question: if the variable is defined in deployment.c, wouldn't the awk part lead to a redefinition of the variable after it is copied in sizes.c?

**Comment by sduverger** [comment]
I generated it in "sizes.c" as it is related to size questions :) If you also generate it in “deployment.c" obviously there will be a conflict.

Whatever your AADL generated does, this should not impact the compilation phase of the "generated" code, as the one-liner is called during final compilation phase.

I think you should take the decision on your own, whether or not doing it in the Makefile or in the perl configuration script (which i think is the best option as it is responsible for port names generation too).

By the way i didn't see the "#ifdef" around the "extern" definition of the "pok_port_names_max_len" in "syscall.c". Did you commit it ? It is mandatory, because if we do not make uses of POK ports in an example, there will be no definition of the variable outside "syscall.c".

**Comment by Etienne13** [comment]
I just did the push
