### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by juli1** [pok-kernel/pok#18]
Since commit https://github.com/pok-kernel/pok/commit/6b048704cbf0092b2082c1682aaadea65bc42ab8

The build is failing. See the badge on the page.

Can we investigate and fix the build. Or revert the change?

**Comment by Etienne13** [comment]
Hi Julien,

how can I run the test cases?

The objective of this commit is to have incremental build, i.e. not to re-build the whole system each time you modify a set of files. I think we should fix the regression and keep this commit.

My guess is that the build fails on the regression tests because two systems are built in a row without a clean in between. The best solution would be to put the path to "deployment.h" in the COPTS option, and to define GENERATED_CODE_PATH. The latter might be useless, I initially put it to allow a simple fix: call make clean all instead of make all.

I you tell me how the regression tests work, I will propose a fix.

**Comment by juli1** [comment]
`make tests` at the root directory should be ok.

You can also look at the build history here: https://travis-ci.org/pok-kernel/pok/builds

You can look at the tests running on the config file here:

https://github.com/pok-kernel/pok/blob/master/.travis.yml

**Comment by juli1** [comment]
So mostly the following: 

```
cd examples/mutexes && make
cd examples/semaphores && make
```

Also, we should probably switch to a better development approach - will work on this if I have some time.

**Comment by Etienne13** [comment]
I think I fixed the issue for building the tests (at least mutexes and semaphores).

The build error now is: "The command "code-inspector -v" exited with 127."

I guess this is not related to commit 6b04870. Is it? Can we close this issue?

**Comment by juli1** [comment]
oh yep - code-inspector has now new tools and this one has been deprecated. Closing.
